version: '3.7'
services:
  backend:
    container_name: backend-con
    restart: unless-stopped
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    depends_on:
      - "postgres"
    ports:
      - "3001:3001"
    volumes:
      - .:/musikcull
    networks:
      musikcull_net:

  postgres:
    image: postgres:11
    container_name: postgres-con
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: musikcull_development
      DATABASE_URL: postgresql://localhost:5432/db
    expose:
      - "5432"
    networks:
      musikcull_net:
    volumes:
      - db_data:/var/lib/postgresql/data

networks:
  musikcull_net:

volumes:
  db_data:

